### ISSUE TITLE
Boolean ftn 

### ISSUE THREAD

**Issue by sophiamazurek** [IsiBee/meal-plan-challenge#11]
In models not too sure how to write ftn, if we could do this part tonight that would be great!

I know how to write the ftn but what to put for the int to make it true/false not too sure what we want to put

**Comment by albenchris** [comment]
Is ftn short for function?

**Comment by albenchris** [comment]
https://sequelize.org/master/manual/model-basics.html#boolean

based on this, I think you set the DataType to BOOLEAN
