### ISSUE TITLE
Build Models

### ISSUE THREAD

**Issue by IsiBee** [IsiBee/meal-plan-challenge#4]
- Recipe
ID Primary Key Integer Auto Increment
Name String
Description String
Prep Time Integer 
Cook Time Integer
Cooking Instructions String
IsSpicy Boolean
Ingredient_id Integer
weekday (can be null)
user_id

- Ingredient
ID primary Key int auto increment
Name String
IsGlutenFree Boolean
IsVegetarian Boolean
IsVegan Boolean
IsKeto Boolean

- User
ID primary key int auto increment
Username String
Email 
Password

**Comment by IsiBee** [comment]
Add weekday field to recipe model (sorry Sophia)

**Comment by albenchris** [comment]
I'm working on a MealPlan model

currently researching e-commerce shopping carts to apply similar datatypes for our app
