### ISSUE TITLE
API Routes

### ISSUE THREAD

**Issue by IsiBee** [IsiBee/meal-plan-challenge#5]
Recipes:
GET 
POST
DELETE - can only delete your own 
PUT

Ingredients:
GET 
POST
DELETE - can only delete your own
PUT

Quantity:
GET
POST
DELETE - can only delete your own
PUT

User:
Login - POST
Logout - POST
GET
POST - signup
DELETE?
PUT?

**Comment by albenchris** [comment]
We're planning on cancelling the Quantity model, right?

I can create routes for Comment models in place.
